#!/bin/bash
#SBATCH --job-name=sn50
#SBATCH --partition=epyc
## No MPI:
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --mail-type=FAIL,END,INVALID_DEPEND,TIME_LIMIT,TIME_LIMIT_90
#SBATCH --mail-user=dylan.jones@student.uni-augsburg.de
#SBATCH --time=7-0
#SBATCH --mem=4gb

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
export OMP_PROC_BIND=false
export OMP_STACKSIZE=256M
ulimit -Ss unlimited


echo - Host machine:\ \ \ $HOSTNAME
echo - I/O directory:\ \ $PWD
echo - SCF directory:\ \ $SCFDIR
echo - Calculation started:\ \ `date`
echo - PATH:\ \ $PATH
echo - E_RAND:\ \ $E_RAND

time ../../../EMTO5.8.1/kgrn/kgrn_cpa < co3sn2s2.dat


echo
echo - Calculation finished: `date`
